apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-pv
  # persistentVolumeClaimが、ラベルを指定してvolumeを利用できるため
  # labeleをつけておく
  labels:
    type: gce-pv
    environment: stg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    # 単一ノードからのみ、read writeが可能
    - ReadWriteOnce
  # PersistentVolumeClaimが削除された際に、PersistentVolumeをどうするのかを指定したもの
  # Retainは、PersistentVolumeを消さずに保持する
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  # 事前にGCPの永続化ディスクを作成しておく必要がある
  # その事前に作成したディスク名を指定
  gcePersistentDisk:
    pdName: sample-gce-pv
    fsType: ext4
