version: '3.9'
services:
  hazelcast-1:
    image: hazelcast/hazelcast:5.3.0
    ports:
      - 5701:5701
    environment:
      HZ_CLUSTERNAME: hello-world
  hazelcast-2:
    image: hazelcast/hazelcast:5.3.0
    ports:
      - 5702:5701
    environment:
      HZ_CLUSTERNAME: hello-world
  hazelcast-3:
    image: hazelcast/hazelcast:5.3.0
    ports:
      - 5703:5701
    environment:
      HZ_CLUSTERNAME: hello-world
  hazelcast-console:
    image: hazelcast/management-center:latest-snapshot
    ports:
      - 8080:8080
